version: '3.8'
services:
  app:
    build: .
    ports:
      - "5432:5432"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=cinedelices
      - DB_PASSWORD=cinedelices
      - DB_NAME=cinedelices
      - JWT_SECRET=votre_secret_jwt
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /node_modules

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cinedelices
      - POSTGRES_PASSWORD=cinedelices
      - POSTGRES_DB=cinedelices
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

volumes:
  postgres_data: