BEGIN;

-- suppression des tables si elles existent déjà

DROP TABLE IF EXISTS "user", "category", "movie", "ingredient", "difficulty", "recipe", "recipe_has_ingredient";


CREATE TABLE "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pseudo" text NOT NULL, 
  "email" varchar(255) UNIQUE NOT NULL,
  "password" text NOT NULL,
  "firstname" text,
  "lastname" text,
  "role" text DEFAULT 'member', -- Ajout du champ role
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

CREATE TABLE "category" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "genre" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "movie" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    "genre" TEXT NOT NULL,
    "year" DATE NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "ingredient" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "label" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "difficulty" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "label" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "recipe" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL, 
    "description" TEXT NOT NULL,
    "duration" INTEGER NOT NULL,
    "image" TEXT,
    "difficulty_id" INTEGER NOT NULL REFERENCES "difficulty"("id"),
    "category_id" INTEGER NOT NULL REFERENCES "category"("id"),
    "movie_id" INTEGER NOT NULL REFERENCES "movie"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);


CREATE TABLE "recipe_has_ingredient" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "recipe_id" INTEGER NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
    "ingredient_id" INTEGER NOT NULL REFERENCES "ingredient"("id") ON DELETE CASCADE,
    "quantity" FLOAT NOT NULL,
    "unity" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    UNIQUE("recipe_id", "ingredient_id")
);
BEGIN;

COMMIT;

